'use client';
import { useState } from 'react';
import { ChevronDown, ChevronUp, Copy, Check, Calculator } from 'lucide-react';
import { PageTransition } from '@/components/shared/PageTransition';

type Role = 'model' | 'photographer';
type Experience = 'new' | 'emerging' | 'established' | 'top';
type UsageType = 'editorial' | 'commercial' | 'social' | 'tv' | 'billboard';
type Market = 'tier1' | 'tier2' | 'international';
type Duration = 'half-day' | 'day' | '2days' | 'week';

// Base day rates (USD) — [model, photographer]
const BASE: Record<Experience, [number, number]> = {
  new:         [300,  500],
  emerging:    [800,  1200],
  established: [2000, 3000],
  top:         [5000, 6000],
};

const USAGE_MULTIPLIER: Record<UsageType, number> = {
  editorial:  1.0,
  social:     1.2,
  commercial: 1.8,
  billboard:  2.5,
  tv:         3.5,
};

const MARKET_MULTIPLIER: Record<Market, number> = {
  tier2:         0.7,
  tier1:         1.0,
  international: 1.4,
};

const DURATION_MULTIPLIER: Record<Duration, number> = {
  'half-day': 0.6,
  'day':      1.0,
  '2days':    1.85,
  'week':     4.0,
};

const EXPERIENCE_LABELS: Record<Experience, string> = {
  new:         'New / Just Starting Out',
  emerging:    'Emerging (1–3 years)',
  established: 'Established (3–7 years)',
  top:         'Top Talent (7+ years / agency)',
};

const USAGE_LABELS: Record<UsageType, string> = {
  editorial:  'Editorial / Press',
  social:     'Social Media',
  commercial: 'Commercial Print / E-commerce',
  billboard:  'Billboard / OOH',
  tv:         'TV / Video Ad',
};

const MARKET_LABELS: Record<Market, string> = {
  tier2:         'Secondary Market (regional)',
  tier1:         'Major Market (NYC, LA, Paris, London)',
  international: 'International Campaign',
};

const DURATION_LABELS: Record<Duration, string> = {
  'half-day': 'Half Day (4 hrs)',
  'day':      'Full Day (8 hrs)',
  '2days':    '2-Day Shoot',
  'week':     'Full Week',
};

function fmt(n: number) {
  return new Intl.NumberFormat('en-US', { style: 'currency', currency: 'USD', maximumFractionDigits: 0 }).format(n);
}

export default function RateCalculatorPage() {
  const [role, setRole] = useState<Role>('model');
  const [experience, setExperience] = useState<Experience>('emerging');
  const [usage, setUsage] = useState<UsageType>('commercial');
  const [market, setMarket] = useState<Market>('tier1');
  const [duration, setDuration] = useState<Duration>('day');
  const [showExplainer, setShowExplainer] = useState(false);
  const [copied, setCopied] = useState(false);

  const roleIdx = role === 'model' ? 0 : 1;
  const base = BASE[experience][roleIdx];
  const estimated = Math.round(
    base * USAGE_MULTIPLIER[usage] * MARKET_MULTIPLIER[market] * DURATION_MULTIPLIER[duration]
  );
  const low = Math.round(estimated * 0.8);
  const high = Math.round(estimated * 1.25);

  async function copyEstimate() {
    const text = `${role === 'model' ? 'Model' : 'Photographer'} Rate Estimate\n${EXPERIENCE_LABELS[experience]} · ${USAGE_LABELS[usage]} · ${MARKET_LABELS[market]} · ${DURATION_LABELS[duration]}\nEstimated range: ${fmt(low)} – ${fmt(high)}\nGenerated by Kailani Rate Calculator`;
    await navigator.clipboard.writeText(text);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  }

  return (
    <PageTransition>
    <div className="max-w-2xl mx-auto py-10 px-4 space-y-8">
      {/* Header */}
      <div>
        <div className="flex items-center gap-2 mb-1">
          <Calculator size={20} className="text-pink-500" />
          <h1 className="text-2xl font-bold tracking-tight">Rate Calculator</h1>
        </div>
        <p className="text-sm text-muted-foreground">Estimate fair market rates for modeling and photography work. These are guidelines — actual rates vary by negotiation.</p>
      </div>

      {/* Inputs */}
      <div className="rounded-2xl border bg-card p-6 space-y-5">
        {/* Role toggle */}
        <div>
          <label className="text-sm font-medium mb-2 block">I am a…</label>
          <div className="flex gap-2">
            {(['model', 'photographer'] as Role[]).map((r) => (
              <button
                key={r}
                onClick={() => setRole(r)}
                className={`flex-1 py-2 rounded-xl text-sm font-semibold border transition-all ${role === r ? 'bg-pink-500 text-white border-pink-500' : 'bg-background text-foreground border-border hover:border-pink-300'}`}
              >
                {r.charAt(0).toUpperCase() + r.slice(1)}
              </button>
            ))}
          </div>
        </div>

        {/* Experience */}
        <SelectField
          label="Experience Level"
          value={experience}
          onChange={(v) => setExperience(v as Experience)}
          options={Object.entries(EXPERIENCE_LABELS).map(([k, v]) => ({ value: k, label: v }))}
        />

        {/* Usage */}
        <SelectField
          label="Usage Type"
          value={usage}
          onChange={(v) => setUsage(v as UsageType)}
          options={Object.entries(USAGE_LABELS).map(([k, v]) => ({ value: k, label: v }))}
        />

        {/* Market */}
        <SelectField
          label="Market"
          value={market}
          onChange={(v) => setMarket(v as Market)}
          options={Object.entries(MARKET_LABELS).map(([k, v]) => ({ value: k, label: v }))}
        />

        {/* Duration */}
        <SelectField
          label="Duration"
          value={duration}
          onChange={(v) => setDuration(v as Duration)}
          options={Object.entries(DURATION_LABELS).map(([k, v]) => ({ value: k, label: v }))}
        />
      </div>

      {/* Result */}
      <div className="rounded-2xl border-2 border-pink-200 bg-pink-50 dark:bg-pink-950/20 p-6 text-center space-y-2">
        <p className="text-sm text-muted-foreground uppercase tracking-widest font-medium">Estimated Rate</p>
        <div className="text-4xl font-bold text-pink-600 dark:text-pink-400">{fmt(low)} – {fmt(high)}</div>
        <p className="text-xs text-muted-foreground">midpoint {fmt(estimated)} · for {DURATION_LABELS[duration].toLowerCase()}</p>
        <div className="flex gap-2 justify-center pt-2">
          <button
            onClick={copyEstimate}
            className="flex items-center gap-1.5 h-9 px-4 rounded-xl text-sm font-semibold border border-pink-300 text-pink-600 hover:bg-pink-100 dark:hover:bg-pink-900/30 transition-colors"
          >
            {copied ? <><Check size={14} /> Copied!</> : <><Copy size={14} /> Copy estimate</>}
          </button>
        </div>
      </div>

      {/* Explainer accordion */}
      <div className="rounded-2xl border overflow-hidden">
        <button
          onClick={() => setShowExplainer((v) => !v)}
          className="w-full flex items-center justify-between p-4 text-sm font-semibold hover:bg-muted/50 transition-colors"
        >
          <span>What affects my rate?</span>
          {showExplainer ? <ChevronUp size={16} /> : <ChevronDown size={16} />}
        </button>
        {showExplainer && (
          <div className="p-4 pt-0 space-y-3 text-sm text-muted-foreground border-t">
            <ExplainerItem title="Experience & Portfolio">
              Your years of experience, the strength of your portfolio, and whether you have agency representation are the biggest factors. Established talent with strong editorial books command significantly higher rates.
            </ExplainerItem>
            <ExplainerItem title="Usage Rights">
              How an image is used matters more than how long the shoot takes. A TV commercial or national billboard requires a much higher fee than editorial press usage, because the commercial value to the brand is far greater.
            </ExplainerItem>
            <ExplainerItem title="Market & Location">
              Rates in NYC, LA, Paris, and London are significantly higher than regional markets. International campaigns often carry a premium because of broader reach and usage.
            </ExplainerItem>
            <ExplainerItem title="Exclusivity">
              If a brand wants to prevent you from working with their competitors (exclusivity), add 20–50% to your rate for the exclusivity period.
            </ExplainerItem>
            <ExplainerItem title="Usage Duration">
              Rates shown are for perpetual usage in the specified category. For time-limited usage (e.g., 6 months digital only), negotiate a lower fee with a renewal option.
            </ExplainerItem>
            <ExplainerItem title="Usage Geography">
              North America or Europe-only campaigns typically pay less than worldwide campaigns. Add 30–50% for worldwide usage rights.
            </ExplainerItem>
          </div>
        )}
      </div>

      <p className="text-xs text-center text-muted-foreground">
        Rates are estimates based on industry guidelines. Always negotiate based on your individual experience, the specific brief, and current market conditions.
      </p>
    </div>
    </PageTransition>
  );
}

function SelectField({ label, value, onChange, options }: {
  label: string;
  value: string;
  onChange: (v: string) => void;
  options: { value: string; label: string }[];
}) {
  return (
    <div>
      <label className="text-sm font-medium mb-1.5 block">{label}</label>
      <select
        value={value}
        onChange={(e) => onChange(e.target.value)}
        className="w-full h-10 rounded-xl border border-border bg-background px-3 text-sm focus:outline-none focus:ring-2 focus:ring-pink-400"
      >
        {options.map((o) => (
          <option key={o.value} value={o.value}>{o.label}</option>
        ))}
      </select>
    </div>
  );
}

function ExplainerItem({ title, children }: { title: string; children: React.ReactNode }) {
  return (
    <div>
      <p className="font-semibold text-foreground mb-0.5">{title}</p>
      <p>{children}</p>
    </div>
  );
}
